window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'r;gc\/24479126-6666cb8c';
window.___jsl.l=[];
window.__GOOGLEAPIS=window.__GOOGLEAPIS||{};
window.__GOOGLEAPIS.gwidget=window.__GOOGLEAPIS.gwidget||{};
window.__GOOGLEAPIS.gwidget.superbatch=false;window.__GOOGLEAPIS.iframes=window.__GOOGLEAPIS.iframes||{};
window.__GOOGLEAPIS.iframes.plusone=window.__GOOGLEAPIS.iframes.plusone_m=window.__GOOGLEAPIS.iframes.plusone||{url:':socialhost:/u/:session_index:/_/+1/fastbutton',params:{count:'',size:'',url:''}};window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window['___jsl'] = window['___jsl'] || {};window['___jsl']['u'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone'];window['___jsl']['ms'] = 'https://plus.google.com';(window['___jsl']['ci'] = (window['___jsl']['ci'] || [])).push({"gwidget":{"parsetags":"onload","superbatch":false},"iframes":{"sharebox":{"params":{"json":"&"},"url":":socialhost:/u/:session_index:/_/sharebox/dialog"},":socialhost:":"https://plusone.google.com","plusone_m":{"url":":socialhost:/u/:session_index:/_/+1/fastbutton","params":{"count":"","size":"","url":""}},"card":{"params":{"style":"#","userid":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/card"},"plusone":{"url":":socialhost:/u/:session_index:/_/+1/fastbutton","params":{"count":"","size":"","url":""}}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"pos.plusones.get":true,"chili.people.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"pos.plusones.delete":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"root-1p":"https://clients6.google.com","root":"https://www.googleapis.com","xd3":"/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","auth":{"useInterimAuth":false}}});var gapi=window.gapi||{};gapi.client=window.gapi&&window.gapi.client||{};
(function(){var r=void 0,n=void 0,w="___jsl",I="h",s="l",J="m",x="ms",y="cu",z="c",K="o",L="p",t="https://ssl.gstatic.com",M="/webclient/js",N="/webclient/jsx/",A="https://apis.google.com",B=".js",O="gcjs-3p",P=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?(\/[\w.,:!=/-]*)(\?[^#]*)?(#.*)?$/,C=/^[?#]([^&]*&)*jsh=([^&]*)/,D="d",p="r",Q="f",u="m",R="n",S="sync",T="callback",E="config",F="nodep",q="gapi.load: ",v=function(e,g){r&&r(e,g);throw q+e+(g&&" "+g);},G=function(e){n&&n(e);var g=window.console;g&&g.warn(q+
e)},H=function(e){e.sort();for(var g=0;g<e.length;)!e[g]||g&&e[g]==e[g-1]?e.splice(g,1):++g},U=function(e){if(document.readyState!="loading")return false;if(typeof window.___gapisync!="undefined")return window.___gapisync;if(e&&(e=e[S],typeof e!="undefined"))return e;for(var e=document.getElementsByTagName("meta"),g=0,j;j=e[g];++g)if("generator"==j.getAttribute("name")&&"blogger"==j.getAttribute("content"))return true;return false},V=function(e,g){var j,k={};typeof g!=="function"?(k=g||{},j=k[T]):
j=g;var m=window[w]=window[w]||{},o=e.split(":");k[F]||H(o);var a=m[s]=m[s]||[];H(a);var c,d=window.location.search,f=window.location.hash;c=m[I];if(d=d&&C.exec(d)||f&&C.exec(f))try{c=decodeURIComponent(d[2])}catch(r){G("Invalid hint "+d[2])}c||v("No hint present","");for(var b,d=true,h=f=0,l;d&&(b=o[f])&&(l=a[h]);)b==l?++f:b<l&&(d=false),++h;b=d&&!b;if(!b){b=c.split(";");a:{c=o;d=a;h=b;a=m;f=k;b=h.shift();l=b==p?t:b==u?a[x]||A:(l=h.shift())&&l.replace(/\/+$/,"");var i;b==p?(i=h.shift(),i=(i.indexOf(N)?
M+"/":"")+i):i=h.shift();var n=b==D,q=n&&h.shift()||O,h=n&&h.shift();if(b==D)f=i,i=q,c="/"+c.join(":")+(d.length?"!"+d.join(":"):"")+B+"?container="+i+"&c=2&jsload=0",f&&(c+="&r="+f),h=="d"&&(c+="&debug=1");else if(b==p||b==Q)f=i,c=(f.indexOf("/")?"/":"")+f+"/"+c.join("__")+(d.length?"--"+d.join("__"):"")+B;else if(b==u||b==R)d=i,c=c.join(",").replace(/\./g,"_").replace(/-/g,"_"),c=d.replace("__features__",c),c=f[F]?c.replace("/d=1/","/d=0/"):c;else{G("Unknown hint type "+b);a="";break a}if(l){l+=
c;c=l;d=a;a=P.exec(c);if(!(f=!a))if(!(f=!!/\.\.|\/\//.test(a[4]))){b:if(f=c,a=a[2],b==p)a=f.substr(0,t.length)==t;else if(b==u)a=d[x]||A,a=f.substr(0,a.length)==a;else{b=d[J];if(a&&b){b=b.split(",");d=0;for(f=b.length;d<f;++d)if(h=b[d],i=a.lastIndexOf(h),(i==0||h.charAt(0)=="."||a.charAt(i-1)==".")&&a.length-h.length==i){a=true;break b}}a=false}f=!a}f&&v("Invalid URI",c);a=l}else a=""}k[E]&&(m[y]=m[y]||[]).push(k[E]);if(a){j&&(m[z]?v("Pending callback",a):(m[L]=o,m[z]=j,m[K]=1));[].push.apply(m[s],
o);U(k)?document.write('<script src="'+a+'"><\/script>'):(k=a,j=document.createElement("script"),j.setAttribute("src",k),k=document.getElementsByTagName("script")[0],k.parentNode.insertBefore(j,k));return}}j&&j.call(null)};gapi.loader={load:V}})();
gapi.load=gapi.loader.load;
(window.gapi=window.gapi||{}).load=gapi.load;
gapi.load('googleapis.client:plusone', {'callback': window['__bsld']  });