// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000024-2)
Ads_Build='00000024-2';var bA,cA,dA,eA,fA,gA,hA,iA,jA,kA,lA,mA,nA,oA,pA;NUM_FARM=1;bA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'','http://a.as-us.falkag.net' ,'','','','','',''];cA=['http://a.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'','https://s.as-us.falkag.net' ,'','','','','',''];dA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'','http://a.as-us.falkag.net' ,'','','','','',''];eA=['http://a.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'','https://s.as-us.falkag.net' ,'','','','','',''];fA=['http://bw.as-test.falkag.net' ,'http://bw.as-eu.falkag.net' ,'','http://bw.as-us.falkag.net' ,'','','','','',''];gA=['http://bw.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'','https://s.as-us.falkag.net' ,'','','','','',''];hA=['http://red.as-test.falkag.net' ,'http://red.as-eu.falkag.net' ,'','http://red.as-us.falkag.net' ,'','','','','',''];iA=['http://red.as-test.falkag.net' ,'https://red.as-eu.falkag.net' ,'','https://red.as-us.falkag.net' ,'','','','','',''];jA=['http://sel.as-test.falkag.net/server/asldata.js','http://data.as-eu.falkag.net/server/asldata.js','','http://sel.as-us.falkag.net/server/asldata.js' ,'','','','','',''];kA=['http://sel.as-test.falkag.net/server/asldata.js','https://as1.falkag.de/server/asldata.js' ,'','https://sel.as-us.falkag.net/server/asldata.js','','','','','',''];lA=['.as-test.falkag.net' ,'.as-eu.falkag.net' ,'','.as-us.falkag.net' ,'','','','','',''];mA=['Falk AdSolution' ,'AdSolution' ,'','Falk AdSolution' ,'','','','','',''];nA=['/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'','/dat/bgf/trpix.gif?' ,'','','','','',''];oA=['/red?cmd=red&' ,'/red?cmd=red&' ,'','/red?cmd=red&' ,'','','','','',''];pA=['/red?cmd=url&' ,'/red?cmd=url&' ,'','/red?cmd=url&' ,'','','','','',''];// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000024-2)
function yC(Ua)
{document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+Ua+'"></scr'+'ipt>');}function zC()
{var Va=this.location.hostname.toLowerCase();var Wa=Va;intPos1=Va.indexOf('.');if (intPos1==-1)
{Wa='';}else
{if((intPos1>=0)&&(intPos1<Va.length))
{intPos2=Va.indexOf('.',intPos1+1);if(intPos2>intPos1)
Wa=Va.substring(intPos1+1,Va.length);}if ((Wa.lastIndexOf('.')==Wa.indexOf('.'))&&Wa.lastIndexOf('.')<3)
Wa=Va;}return Wa;}function aD()
{var Wa=zC();if(Wa=='')
return 'D'+this.location.hostname;else
return 'D'+Wa;}function bD(Xa)
{var Wa=zC();if(Xa==-1)
{	 if(Wa!='')
	 Wa=' domain='+Wa;	return ';path=/;'+Wa;}var Ya=new Date();if(Wa!='')
Wa=';domain='+Wa;Ya.setTime(parseInt(Ya.getTime(),10)+1000*60*parseInt(Xa,10));return ';path=/;expires='+Ya.toGMTString()+Wa;}function cD(c,d,v)
{if(sA!=-1) var intBwdTyp=KAS[sA][4][27];if(typeof(intBwdTyp)=='undefined')
intBwdTyp=0;var b='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+c+','+d+'&kid='+c+'&chw='+qA+'&tcs='+rA+v+((xC( Ads_iid,c )&&(uB>0))?tB:'')+vA;var Za='&sta=';b+='&dmn='+Ads_T[5];if(navigator.appVersion.substring(0,1)>'3')
{b+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;Za+=',,,'+(navigator.javaEnabled()?'1':'0');if(navigator.javaEnabled())
b+='&jav=1';}else
Za+=',,,';var Ab=new Date();Za+=',,,,,,';if((Ads_wrd!='')&&(Ads_wrd.toLowerCase()!='[keyword]'))
{b+='&wrd='+escape(Ads_wrd);Za+='';}Za+=','+sE[10]+','+Ads_T[13]+','+intBwdTyp+','+Ads_T[4]+','+Ads_T[10]+','+Ads_T[11]+','+Ads_T[3]+','+Ads_T[12];b+=Za;if(gbolSUXX25067) b+='&trglog='+escape(gstrXarrTargetDaten);return (Ads_Timestamp+b);}function dD(c,d,v)
{return '&rdm='+cD(c,d,v)+'&iid='+Ads_iid+'&bid='+d;}function eD()
{if (typeof(gB[Ads_sec])=='undefined')
tC();return gB[Ads_sec]+(yA?oA[NUM_FARM]+'flg='+wC()+'&dat='+fB[Ads_sec]+'/dat/bgf/trpix.gif&':nA[NUM_FARM]);}function fD()
{return gB[Ads_sec]+nA[NUM_FARM]+'cmd=req&';}function gD(Bb,b)
{if (Bb==0)
{lD(1,'',eD()+b);return ((Ads_opt&512)>0)?'':(pD('Ads_Count'+Ads_iid)+'<img src="'+eD()+b+'" width="1" height="1">'+qD());}else if (Bb==1)
{lD(1,'Request tracking URL',fD()+b);return pD('Ads_ReqCount'+Ads_iid)+'<img src="'+fD()+b+'" width="1" height="1">'+qD();}}function hD(q,b)
{q.document.write(gD(0,b));}function iD()
{return jD(Math.random()*100000000,8);}function jD(Cb,Db)
{var Eb='#'+(Cb+100000000);return Eb.substr(10-Db,Db);}function kD(Fb,Gb,Hb)
{var l;while((l=Fb.indexOf(Gb))!=-1)
Fb=Fb.substr(0,l)+Hb+Fb.substring(l+Gb.length,Fb.length);return Fb;}function lD(z,Fb,Ib)
{var Jb=new Date();if(Ads_debug==1)
{document.write(((z!=3)?'':'<br>')+'<font color=#0000ff>[DEBUG'+((Jb-wA)/1000)+']</font> ');if((z==0)||(z==3))
document.write('<b><big>'+Fb+'</big></b><br>');else if(z==1)
document.write(''+Fb+': &nbsp;<font color=#000080>'+Ib+'</font><br>');else
document.write('<b>'+Fb+'</b><br>');}else if((Ads_debug==2)&&(z==3))
document.write('<font color=#0000ff>[DEBUG'+((Jb-wA)/1000)+']</font> <b><big>'+Fb+'</big></b><br>');}function mD(Kb)
{var y='#'+(parseInt(Kb,10)+100000000);return y.substr(2,2)+'/'+y.substr(4,2)+'/'+y.substr(6,2)+'/'+y.substr(8,2);}function nD(Cb)
{var Lb='0123456789ABCDEF';var Mb='';while(Cb>0)
{Mb=Lb.substr(Cb%16,1)+Mb;Cb=parseInt(Cb/16,10);}return (Mb=='')?'0':Mb;}function oD(Ga)
{var Nb;var Ob=0;if(aB>-1)
{Ob=aB;return Ob;}if((Ga==0)&&((Ads_opt&2048)>0))
return -1;if((navigator.userAgent.indexOf("Opera")!=-1)||((navigator.appName=="Netscape")&&(navigator.userAgent.indexOf("Mozilla")!=-1)&&(parseFloat(navigator.appVersion)>=4)))
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{Nb=navigator.plugins['Shockwave Flash'].description;Nb=Nb.substring(Nb.indexOf("."),-1);Ob=Nb.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Mac")!=-1&&document.all)
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{Nb=navigator.plugins['Shockwave Flash'].description;Nb=Nb.substring(Nb.indexOf("."),-1);Nb=Nb.substring(Nb.length-1,Nb.length);Ob=Nb.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Windows")!=-1&&navigator.userAgent.indexOf("Windows 3")==-1&&document.all)
{document.write('<scr'+'ipt language=VBScript>\n Ads_vbCV=10\nAds_vbMV=1\nDo\nOn Error Resume Next\n');document.write('Ads_vbBF=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash."&Ads_vbCV)))\n');document.write('If Ads_vbBF=true Then Exit Do\nAds_vbCV=Ads_vbCV-1\nLoop While Ads_vbCV>=Ads_vbMV\n </scr'+'ipt>');Ob=Ads_vbCV;}aB=Ob;return Ob;}function pD(Pb)
{if(rB)
return '<div id='+Pb+' style="position:absolute;left:-1000;top:-1000;">';else
return '';}function qD()
{if(rB)
return '</div>';else
return '';}function rD(Qb)
{var Rb,Sb;if(window.innerHeight)
{Rb=Qb.x;Sb=Qb.y;}else
{if(Qb.offsetLeft)
{Qb=Qb;Rb=Qb.offsetLeft;Li=Qb.offsetParent;while(Li!=null)
{Rb+=Li.offsetLeft;Li=Li.offsetParent;}Sb=Qb.offsetTop;Li=Qb.offsetParent;while(Li!=null)
{Sb+=Li.offsetTop;Li=Li.offsetParent;}}else
return [-1000,-1000];}return [Rb,Sb];}function sD(Tb,w,f,g)
{var Ub;var Qb=document.images[w];var Vb=rD(Qb);Qb.width=f;Qb.height=g;if(rB)
Ub=document.getElementById(Tb).style;else if(document.layers)
Ub=document.layers[Tb];else
Ub=document.all[Tb].style;Ub.left=Vb[0];Ub.top=Vb[1];if (rB) Ub.display='block';else if(document.layers) Ub.visibility='show';else Ub.visibility='visible';}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000024-2)
if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=vC;gbolSUXX25067=false;var Ads_ModulMain=true;if(typeof(Ads_ModulEffects)=='undefined')
Ads_ModulEffects=false;var qA,rA,sA,tA,uA,vA,wA,xA;var yA,zA,aB,bB,cB,dB;var eB=false;var fB=[];var gB=[];var hB=[];var iB=[];var jB=[];var kB=[];var lB=[];var mB=navigator.userAgent.toLowerCase();var nB=(mB.indexOf("msie")!=-1);var oB=((mB.indexOf("win")!=-1)||(mB.indexOf("16bit")!=-1));var pB=(mB.indexOf("mac")!=-1);var qB=(navigator.appName.indexOf('icrosoft')!=-1);var rB=(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')?1:0;var sB=true;var tB='';var uB=0;var vB=[];var wB=0;var xB=0;var yB=[];var zB;var aC=[];var bC=[];var cC=[];var dC=[];var eC=[];var fC=[];var gC=[];var hC=[];var Ads_LinkUrl,Ads_CountUrl,Ads_CountUrl_ne,Ads_ClickUrl,Ads_T,Ads_T_OW,iid,bid,rdm;if(typeof(Ads_FXPL)=='undefined'){var Ads_FXPL=false;}Ads_T_OW=[];var iC,jC,Ads_gintCurVersion;var kC='toolbar=yes,directories=yes,status=yes,scrollbars=yes,resizable=yes,menubar=yes,location=yes';function gotoSite(){window.open(iC,'flashwin',kC);}function emosite(){window.open(iC,'flashwin',kC);}function FlashClick(){window.open(iC,'flashwin',kC);}function link1(){window.open(iC,'flashwin',kC);}function gotoURL(a){window.open(jC+escape(a),'flashwin',kC);}function lC()
{Ads_kid=0;Ads_bid=0;Ads_cmd='';}function mC(a)
{a=kD(a,'[par]',escape(Ads_par));a=kD(a,'[keyword]',escape(Ads_wrd));a=kD(a,'[timestamp]',Ads_Timestamp);a=kD(a,'[clickurl]',escape(Ads_CountUrl));a=kD(a,'[clickurl_plain]',Ads_CountUrl);a=kD(a,'[web_id]',Ads_wid);a=kD(a,'[web_external_id]',escape(Ads_xwid));a=kD(a,'[con_id]',Ads_iid);a=kD(a,'[con_external_id]',escape(Ads_xiid));a=kD(a,'[ban_id]',Ads_sbid);a=kD(a,'[cam_id]',tA);return a;}function nC(a,b)
{return gB[Ads_sec]+pA[NUM_FARM]+'flg='+wC()+'&'+b+'&dat='+escape(a);}function oC(c,d,e,f,g)
{var h;if(uB<2)
{uB++;h=uB+1;tB+='&kid'+h+'='+c;tB+='&bid'+h+'='+d;tB+='&iid'+h+'='+Ads_iid;tB+='&dlv'+h+'='+Ads_nid+','+Ads_wid+','+Ads_iid+','+c+','+d;if(uA!=0)
tB+='&sid'+h+'='+uA;arrIntern=e.split('-');wB=arrIntern[1];xB=arrIntern[2];Ads_iid=arrIntern[1];Ads_kid=arrIntern[2];Ads_bid=(arrIntern.length<4)?0:arrIntern[3];Ads_par=(arrIntern.length<5)?Ads_par:unescape(arrIntern[4]);Ads_xp=(arrIntern.length<6||Ads_xp!='')?Ads_xp:arrIntern[5];Ads_yp=(arrIntern.length<7||Ads_yp!='')?Ads_yp:arrIntern[6];Ads_xp1=(arrIntern.length<8||Ads_xp1!='')?Ads_xp1:arrIntern[7];Ads_yp1=(arrIntern.length<9||Ads_yp1!='')?Ads_yp1:arrIntern[8];Ads_xl=0;Ads_yl=0;yC(fB[Ads_sec]+'/dat/cjf/'+mD(Ads_iid)+'.js');}else
{tB='';uB=0;lC();}}function pC(i)
{var j=[];var k=i.length;var l;for(l=0;l<k;l+=2)
j[l/2+1]=Ads_CountUrl+escape(i[l+1])+'&bidx='+i[l];return j;}function SAS()
{tC();uC();if (typeof(Ads_T)!='undefined')
{if((document.cookie.toLowerCase().indexOf('bndlvl')==-1)&&((IAS[13]&4)>0))
rE();else
qC();}else
{sB=false;lD(1,'Waiting for asldata.','');}}function qC()
{var m;if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=vC;if(((Ads_nid==631)||(Ads_nid==668))&&(NUM_FARM==1))
{ fB[0]=['http://e.as-eu.falkag.net'];iB[0]=fB[0];}if((Ads_nid==80)&&(NUM_FARM==3))
{ fB[0]=['http://e.as-us.falkag.net'];iB[0]=fB[0];}var n='undefined';for (intI=0;intI<Ads_T.length;intI++)
{if (typeof(Ads_T_OW)!=n)
{if (typeof(Ads_T_OW[intI])!=n)
{lD(1,'Overwriting Targeting AdsT['+intI+'] ('+Ads_T[intI]+') with',Ads_T_OW[intI]);Ads_T[intI]=Ads_T_OW[intI];}}}if(typeof(Ads_cmd)==n) Ads_cmd='';if(typeof(Ads_kid)==n) Ads_kid=0;if(typeof(Ads_bid)==n) Ads_bid=0;if(typeof(Ads_xl)==n) Ads_xl=0;if(typeof(Ads_yl)==n) Ads_yl=0;if(typeof(Ads_xp)==n) Ads_xp='';if(typeof(Ads_yp)==n) Ads_yp='';if(typeof(Ads_xp1)==n) Ads_xp1='';if(typeof(Ads_yp1)==n) Ads_yp1='';if(typeof(Ads_opt)==n) Ads_opt=0;if(typeof(Ads_wrd)==n) Ads_wrd='';if(typeof(Ads_prf)==n) Ads_prf='';if(typeof(Ads_par)==n) Ads_par='';if(typeof(Ads_cnturl)==n) Ads_cnturl='';if(typeof(Ads_ref)==n) Ads_ref=0;if(typeof(Ads_anc)==n) Ads_anc='';if(typeof(Ads_cmb)==n) Ads_cmb=[];if(typeof(Ads_uid)==n) Ads_uid='';if(typeof(Ads_bgc)==n) Ads_bgc='';Ads_cmd=Ads_cmd.toLowerCase();if(Ads_ref==0)
Ads_ref=IAS[12];if(Ads_bgc=='')
{if(typeof(IAS[16])!=n)
Ads_bgc=IAS[16];}m=fB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+Ads_kid+'&wrd='+escape(Ads_wrd) +'&bid='+Ads_bid+'&prf='+escape(Ads_prf) +'&xl='+Ads_xl+'&par='+escape(Ads_par) +'&yl='+Ads_yl+'&cnturl='+Ads_cnturl+'&debug='+Ads_debug +'&xp='+Ads_xp+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+Ads_yp+'&ref='+Ads_ref +'&xp1='+Ads_xp1+'&yp1='+Ads_yp1+'&opt=';var o='" width="'+Ads_xl+'" height="'+Ads_yl+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>';if(Ads_ref>0)
{document.write('<iframe src="'+m+Ads_opt+o);Ads_ref=0;return;}aF();if((Ads_bgc!='')&&(Ads_bgc!='-1'))
document.body.style['backgroundColor']='#'+Ads_bgc;if(((IAS[13]&8)>0)&&(sE[10]==0))
oE();qA='';rA='';tA=0;uA=0;vA='';sA=-1;if(NUM_FARM==3)
KAS[KAS.length]=[-1,100,-1,100,[],0,0,0,0,100];if((Ads_kid==0)||(Ads_kid==''))
sA=wD();else
{k=KAS.length;sA=0;while((sA<k)&&(KAS[sA][0]!=Ads_kid))
sA++;if(sA==k)
sA=-1;}if((Ads_opt&256)!=0)
{if(sA!=-1)
Ads_skid=KAS[sA][0];else
Ads_skid=0;}else
{if(sA!=-1)
{tA=KAS[sA][0];uA=KAS[sA][6];if(uA!=0)
vA='&sid='+uA;if(tA>0)
{yC(fB[Ads_sec]+'/dat/bjf/'+mD(tA)+'.js');}else
DAS();}else
{DAS();}}}function DAS()
{var p,k,b,q,r,s,t,u;var v='';var w='';var x=['_blank','_self','_parent','_top'];var d=0;var y,f,g;if(IAS[9]==1)
{y='adsolut.gif';f=234;g=60;}else
{y='trpix.gif';f=1;g=1;}bB=mA[NUM_FARM];if(IAS[9]==4)
bB='Werbung';bB='onmouseover="self.status=\''+bB+'\';return true;" ';if(IAS[9]==5)
bB='';var z=1;var a='http://www.falkag.de';// Ziel-Url
var A='Falk AdSolution';var B=0;var C='';var D='';var E='';var F='';var G='';var H=0;var I=0;var J=0;var K=0;var L=1;var M=2;var e='';var N='';var i=[];var O=0;var P='';var Q='';var R=false;var S=0;var T=false;var U,V,W,X,Y,Z,Aa,Ba,Ca,Da;if(tA!=0)
{if((Ads_bid==0)||(Ads_bid==''))
p=xD(sA,tA);else
{k=BAS.length;p=0;while((BAS[p][0]!=Ads_bid)&&(p<k))
p++;if(p==k)
p=-1;}if(p!=-1)
d=BAS[p][0];}if(d>0)
{z=BAS[p][3];y=BAS[p][4];a=BAS[p][5];A=BAS[p][6];B=BAS[p][12];C=BAS[p][7];D=BAS[p][8];E=BAS[p][9];F=BAS[p][10];G=BAS[p][11];f=BAS[p][13];g=BAS[p][14];H=BAS[p][15];I=BAS[p][16];L=BAS[p][17];M=BAS[p][18];e=BAS[p][19];N=BAS[p][20];i=BAS[p][22];O=BAS[p][23];P=BAS[p][24];Q=BAS[p][25];S=BAS[p][27];if (!eB)
eB=(BAS[p][26]==1);Ads_klist+=tA+'#';s=KAS[sA][4][25];if(s>0)
{if(typeof(Ads_fcount[s])=='undefined')
Ads_fcount[s]=1;else
Ads_fcount[s] ++;}}if(tA>0)
v=cF(tA,sA,d,p,((B&4096)>0));if(tA==-1)
{tA=99999999;d=99999999;}Ads_skid=tA;Ads_sbid=d;D=(D=='')?a:D;U=(B&24);V=x[B&3];Y=((B&64)>0)&&((Ads_opt&64)==0);W=(B&128)>0;X=(B&512)>0;R=(P=='_search')||(P=='_media');Z=((B&1024)>0)&&Ads_ModulEffects;Aa=((B&8192)>0);Si=((Ads_opt&2)>0);Ba=(B&2048)>0;Ca=(N.length>0);T=(S==0)?false:true;f=(Ads_xl>0)?Ads_xl:f;g=(Ads_yl>0)?Ads_yl:g;H=(Ads_xp!='')?Ads_xp:H;I=(Ads_yp!='')?Ads_yp:I;J=(Ads_xp1!='')?Ads_xp1:J;K=(Ads_yp1!='')?Ads_yp1:K;yA=(B&4096)>0;Ads_opt|=(B&16384)>0?64:0;Ads_opt|=IAS[3]*32;if (T&&Ads_cmd!='win')
{var Ea='nid='+Ads_nid+'&iid='+Ads_iid+'&bid='+d+'&rdm='+iD();document.write(gD(1,Ea));}if(Ads_anc!='')
{t=true;w=Ads_anc;Ads_anc='';}Ads_Timestamp=iD();a=mC(a);D=mC(D);if(Ads_cnturl!='')
{Da=kD(Ads_cnturl,'[url]',escape(a));a=kD(Da,'[url_plain]',a);Da=kD(Ads_cnturl,'[url]',escape(D));D=kD(Da,'[url_plain]',D);}if(vB.length!=0)
{qA+=vB[13];rA+=vB[14];}b=dD(tA,d,v);if((z==3)||(z==4)||(z==8))
{Ads_LinkUrl=a;Ads_CountUrl=nC('',b);Ads_CountUrl_ne=Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=';Ads_ClickUrl=Ads_CountUrl+escape(a);Ads_MultiUrl=pC(i);Ads_ViewCode=gD(0,b);Ads_ViewUrl=eD()+b;}if(z==1)
E=iB[Ads_sec]+'/dat/bgf/'+y;if(vB.length!=0)
{if(!W)
{W=vB[0];Y=vB[1];X=vB[2];M=vB[3];Z=vB[4];Aa=vB[5];}if(!Ca)
{Ca=vB[6];N=vB[7];}H=vB[8];I=vB[9];J=vB[16];K=vB[17];U=vB[10];IAS[2]=vB[11];IAS[11]=vB[12];w=vB[15];t=(w!='');vB=[];}if(z==5)
{vB=[W,Y,X,M,Z,Aa,Ca,N,H,I,U,IAS[2],IAS[11],qA,rA,w,J,K];W=false;Ca=false;t=false;IAS[2]=0;}if((Ads_cmd=='lnk')&&(z!=5))
{self.location.href=nC(a,b);W=false;Ca=false;t=false;z=6;return;}if(W&&!R)
{if (!Si)
q=gI(f,g,H,I,U,Y,X,M,Z,Aa,R,'');else
q=window;if(Y)
{if(window.innerHeight)
{f=q.innerWidth;g=q.innerHeight;}else
{f=q.document.body.clientWidth;g=q.document.body.clientHeight;}}if (!Si||(Si&&Ads_cmd=='win'))
if(X&&(M==0))
q.blur();else if(X)
q.setTimeout('window.blur();',M*1000);}else
q=window;if(t)
document.write(pD('Ads_place'+Ads_iid));else if(Ads_ModulEffects&&Ca)
{if(U==16)
U=1;else if(U==24)
U=2;else
U=0;nH(Ads_iid,f,g,H,I,U,N,W,q);oH(Ads_iid,Ads_sec);}lD(1,'Banner-Typ/PopUp',z+'/'+W);iI(tA,d,f,g,H,I,U,Y,X,M,Z,Aa,R,'',Si);if (!Si||(Si&&(Ads_cmd =='win')))
{if(z<2)
aI(q,W,b,E,a,V,f,g,A,R,P,d,H,I);else if(z==2)
bI(q,W,b,y,a,V,f,g,A,C,D,Ba,L,Q);else if(z==3)
cI(q,W,b,tA,d,v,Ca,f,g,O,P,t,'/dat/brf/',0,R,Si);else if(z==4)
dI(q,W,b,F,G,Ca,f,g,t);else if(z==5)
oC(tA,d,e,f,g);else if(z==8)
cI(q,W,b,tA,d,v,Ca,f,g,O,P,t,'/dat/bfx/',parseInt(e,10),R,Si);}lD(3,'Banner-display finished');pE();if(t)
{document.write(qD());setInterval('sD("Ads_place'+Ads_iid+'","'+w+'",'+f+','+g+');',20);}if(Ads_ModulEffects&&Ca)
pH(Ads_iid);if(z!=5)
lC();Ads_idl+='#'+Ads_iid+'#';if((IAS[2]>0)&&(Ads_idl.indexOf('#'+IAS[2]+'#')==-1)&&(IAS[11]>(Math.random()*100)))
{Ads_kid=0;Ads_bid=0;Ads_xl=0;Ads_yl=0;yC(fB[Ads_sec]+'/dat/cjf/'+mD(IAS[2])+'.js');}k=Ads_cmb.length;for(l=0;l<k;l++)
{if(Ads_cmb[l]!='')
{u=Ads_cmb[l];Ads_cmb[l]='';l=k;Ads_pth='';Ads_iid='';eval(u);if(Ads_pth!='')
yC(fB[Ads_sec]+'/dat/njf/'+Ads_pth+'.js');else
yC(fB[Ads_sec]+'/dat/cjf/'+mD(Ads_iid)+'.js');}}}function CAS()
{rC(0);}function CASF()
{var Fa=new Date();Ads_T=[0,0,'',0,0,'','','','',Fa,0,0,0,0];rC(1);}function rC(Ga)
{if(typeof(Ads_debug)=='undefined') Ads_debug=0;var Ha=new Date(Ads_T[9]);var Ia=new Date();Ads_T[9]=Ha-Ia;var Ja=Ads_T[0]+'#'+Ads_T[1]+'#'+Ads_T[2]+'#'+Ads_T[3]+'#'+Ads_T[4]+'#'+Ads_T[5]+'#'+Ads_T[6]+'#'+escape(Ads_T[7])+'#'+escape(Ads_T[8])+'#'+Ads_T[9]+'#'+Ads_T[10]+'#'+Ads_T[11]+'#'+Ads_T[12]+'#'+Ads_T[13];document.cookie='ASLTRG'+NUM_FARM+'='+Ja+bD(60*((Ga==0)? 24:1));lD(1,'Load targeting-infos from server ('+((Ga==0)? 'Origin':'Failover')+')',Ja);if (sB==false)
{SAS();sB=true;}}function LAS(Ka)
{Ads_iid=0;var b='pth='+Ka+'&xl='+Ads_xl+'&yl='+Ads_yl;if(typeof(Ads_channels)!='undefined')
b+='&chn='+escape(Ads_channels);yA=false;document.write(gD(0,b));}function sC()
{wA=new Date();aB=-1;dB=0;document.cookie='BSUID=1'+bD(60*24*30);zA=false;if(typeof(Ads_debug)=='undefined') Ads_debug=0;if(typeof(Ads_sec)=='undefined') Ads_sec=0;if(typeof(Ads_klist)!='string') Ads_klist='';if(typeof(Ads_fcount)!='object') Ads_fcount=[];if(typeof(Ads_idl)!='string') Ads_idl='';if(typeof(garrIFrames)=='undefined') garrIFrames=[];lD(3,'Global Init');lD(1,'VAS Build Version:',Ads_Build);}function tC()
{if(typeof(NUM_FARM)=='undefined')
NUM_FARM=1;if(typeof(Ads_farmid)!='undefined')
NUM_FARM=Ads_farmid;lD(1,'Setting configuration for farm',NUM_FARM);fB=[bA[NUM_FARM],cA[NUM_FARM]];gB=[hA[NUM_FARM],iA[NUM_FARM]];hB=[jA[NUM_FARM],kA[NUM_FARM]];iB=[dA[NUM_FARM],eA[NUM_FARM]];jB=[fA[NUM_FARM],gA[NUM_FARM]];}function uC()
{var Ja=document.cookie+';';var La=(Ja.indexOf('BSUID=')!=-1);var Ma=Ja.indexOf('ASLTRG'+NUM_FARM+'=');var Na,V;if(Ma!=-1)
{Na=Ja.indexOf(';',Ma);V=Ja.substring(Ma+8,Na);Ads_T=V.split('#');Ads_T[7]=unescape(Ads_T[7]);Ads_T[8]=unescape(Ads_T[8]);lD(1,'Load targeting-infos from cookie',V);}else
{lD(1,'#-#ASLDATA-load start','');yC(hB[Ads_sec]+ (La?('?rdm='+iD()):''));lD(1,'#-#ASLDATA-load ende','');}}function vC(Oa,Pa,Qa)
{return true;}function wC()
{var Ra=(yA?1:0);Ra+=((eB)?2:0);lD(1,'FLG',Ra);return Ra;}function xC(Sa,Ta)
{if ((Sa==wB)&&(Ta==xB))
return true;else
return false;}sC();// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000024-2)
function zH(Eg,Mi)
{return (Eg==0)?'':' '+Mi+'="'+Eg+'"';}function aI(q,W,b,E,a,V,f,g,A,R,P,d,H,I)
{E=mC(E);if(W&&R&&!Si)
{m=fB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+tA+'&wrd='+escape(Ads_wrd) +'&bid='+d+'&prf='+escape(Ads_prf) +'&xl='+f+'&par='+escape(Ads_par) +'&yl='+g+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+H+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+I+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';lD(1,'Sidebar',m);qSide=window.open(m,P);}else
{if(W)
eI(q,A);q.document.write('<a href="'+nC(a,b) +'" target="'+V+'" '+bB+'onmouseout="self.status=\'\';return true;">');q.document.write('<img src="'+E+'"'+zH(f,'width')+zH(g,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+A+'"></a>');hD(q,b);if(W)
fI(q);}if (xC(Ads_iid,tA))
{tB='';uB=0;}}function bI(q,W,b,y,a,V,f,g,A,C,D,Ba,L,Q)
{var Pi=kD(b,'&rdm='+Ads_Timestamp,'');if(W)
eI(q,A);a=nC(a,Pi);D=nC(D,Pi);y=iB[Ads_sec]+'/dat/bgf/'+y;C=iB[Ads_sec]+'/dat/bgf/'+C;iC=a;jC=nC('',Pi);var Qi=y;if(typeof(Q)=='undefined') Q='';if(Q=='')
Qi+='?clickTag='+escape(a)+'&url='+escape(a);else if(Q!='0')
Qi+='?'+Q+'='+escape(a);var Nb;if(L<=oD(1))
{q.document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http'+((Ads_sec==1)?'s':'')+'://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0" id=banner'+zH(f,'width')+zH(g,'height')+'">');q.document.write('<PARAM NAME=movie VALUE="'+Qi+'"><PARAM NAME=play VALUE=true><PARAM NAME=autoplay VALUE=true><PARAM NAME=wmode VALUE=opaque><PARAM NAME=quality VALUE=autohigh><PARAM name=scale value=exactfit>');q.document.write('<EMBED src="'+Qi+'" quality=autohigh autoplay=true play=true wmode=opaque scale=exactfit swLiveConnect=TRUE'+zH(f,'width')+zH(g,'height')+' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT>');}else
{q.document.write('<a href="'+D+'" target="'+V+'" '+bB+' onmouseout="self.status=\'\';return true;"><img src="'+C+'"'+zH(f,'width')+zH(g,'height')+' border="0" alt="'+A+'"></a>');}hD(q,b);if(W)
fI(q);if (xC(Ads_iid,tA))
{tB='';uB=0;}}function cI(q,W,b,c,d,v,Ca,f,g,O,P,t,Ka,Ri,R,Si)
{var y=fB[Ads_sec]+Ka+mD((Ri>0)?Ri:((O==0)?d:O));var Ti,Af;iid=Ads_iid;bid=d;rdm=cD(c,d,v);if(W||((Ca||t)&&(qB||rB)))
{var Ui='*';for(Af=1;Af<Ads_MultiUrl.length;Af++)
{a=Ads_MultiUrl[Af];Ui+=a.substring(Ads_CountUrl.length,a.length)+'*';}Ti=Ads_wid+'#'+Ads_iid+'#'+c+'#'+d+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(gB[Ads_sec]+pA[NUM_FARM]+'flg='+wC()+'&')+'#'+Ads_LinkUrl+'#'+Ui+'#'+eD();}if(W&&R&&!Si)
{window.open(y+'.html?'+escape(Ti),P);}else if(W)
{q.location.href=y+'.html?'+escape(Ti);}else if((Ca||t)&&(qB||rB))
{document.write('<iframe src="'+y+'.html?'+escape(Ti)+'" width="'+f+'" height="'+g+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{if(Ri>0)
{Ads_xl=f;Ads_yl=g;hD(q,b);if ((typeof(Ads_FXPL)=='undefined')||(Ads_FXPL==false))
{yC(fB[Ads_sec]+'/dat/dlv/afxplay.js');Ads_FXPL=true;}}yC(y+'.js');}if (xC(Ads_iid,tA))
{tB='';uB=0;}}function dI(q,W,b,F,G,Ca,f,g,t)
{G=mC(unescape(G));F=mC(unescape(F));if(W)
q.location.href=F;else
{if(((Ca||t)&&qB)||(G==''))
document.write('<iframe src="'+F+'" width="'+f+'" height="'+g+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');else
yC(G);}hD(window,b);if (xC(Ads_iid,tA))
{tB='';uB=0;}}function eI(q,A)
{q.document.open();q.document.write('<html><head><title>'+A+'</title></head><body topmargin="0" leftmargin="0" rightmargin="0" marginwidth="0" marginheight="0"><table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td valign="middle"><center>');}function fI(q)
{q.document.write('</center></td></tr></table></body></html>');q.document.close();}function gI(f,g,H,I,U,Y,X,M,Z,Aa,R,P)
{var r='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var Vi='Ads_Popup'+Ads_iid;var Wi,Xi;var Yi=0;var Zi=0;if (!R&&P!='')
Vi=P;r=hI(f,g,H,I,U,Y,X,M,Z,Aa,R,P,Si);if((Ads_opt&32)>0)
Vi+=''+Math.round(Math.random()*100000);q=open('',Vi,r);if(Y&&(!nB))
q.moveTo(0,0);if(Z)
wH(q,f,g);return q;}function hI(f,g,H,I,U,Y,X,M,Z,Aa,R,P,Si)
{var r='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var Vi='Ads_Popup'+Ads_iid;var Wi,Xi;var Yi=0;var Zi=0;if (!R&&P!='')
Vi=P;if(Y)
{if (oB)
{Yi=10;Zi=30;}else if (pB)
{Yi=20;Zi=35;}r+=',scrollbars=no,resizable=no,width='+(screen.availWidth-Yi)+',height='+(screen.availHeight-Zi)+',screenX=0,screenY=0';if(nB)
r='fullscreen=yes';}else
{if(Z)
r+=',resizable=yes,width=90,height=70,innerWidth=90,innerHeight=70';else
r+=',resizable=no,width='+f+',height='+g;if(Aa)
r+=',scrollbars=yes';else
r+=',scrollbars=no';if((Ads_opt&64)>0)
r='locationbar=yes,scrollbars=yes,directories=yes,statusbar=yes,toolbar=yes,location=yes,menubar=yes,personalbar=yes,resizable=yes,width='+f+',height='+g;if(U==16)
{H=(screen.width-f-25)*H/100;I=(screen.height-g-50)*I/100;}else if(U==24)
{H=(screen.width-f-25)*Math.random();I=(screen.height-g-50)*Math.random();}if (!qB)
r+=",screenX="+H+",screenY="+I;else
r+=",left="+H+",top="+I;}return r;}function iI(tA,d,f,g,H,I,U,Y,X,M,Z,Aa,R,P,Si)
{var Aj='';Aj='<scr'+'ipt language="JavaScript">'+'function Ads_PopUp() {';if (Ads_cmd!='win'&&Si&&(d>0))
{lD(1,'POP ON EXIT','');var Vi='Ads_Popup'+Ads_iid;if (!R&&P!='')
Vi=P;if((Ads_opt&32)>0)
Vi+=''+Math.round(Math.random()*100000);r=hI(f,g,H,I,U,Y,X,M,Z,Aa,R,'',true);m=fB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+tA+'&wrd='+escape(Ads_wrd) +'&bid='+d+'&prf='+escape(Ads_prf) +'&xl='+f+'&par='+escape(Ads_par) +'&yl='+g+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+H+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+I+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';kB[kB.length]='q=open(\''+m+'\',\''+Vi+'\',\''+r+'\');';}for (var intI=0 ;intI<kB.length ;intI++)
{Aj+=kB[intI];}Aj+='}'+'</scr'+'ipt>';document.writeln(Aj);}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000024-2)
var sE=[];var tE;function uE(Qf,Rf,Sf)
{if(typeof(Qf)=='undefined')
return [];var l,k;var Tf=[];var Uf=Qf.split('x');var Vf=Uf[0];var Wf=Rf-Vf;var k=Uf.length;for(l=1;l<k;l++)
{Ch=Uf[l].split(':');if(Sf&&(Ch[2]==-1))
Tf[Ch[0]]=[Ch[1],-1];Ch[2]-=Wf;if(Ch[2]>0)
Tf[Ch[0]]=[Ch[1],Ch[2]];}return Tf;}function vE(Tf,Rf)
{var Pb;var Qf=Rf;for(Pb in Tf)
Qf+='x'+Pb+':'+Tf[Pb][0]+':'+Tf[Pb][1];return Qf;}function wE(Xf,Yf)
{while(Xf.length>800)
Xf=Xf.substr(0,Xf.lastIndexOf('#',Xf.length-2)+1);sE[Yf]=Xf;}function xE(Yf,Kb)
{var Zf='111';var Ag='@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`';var k=0;var Bg='#'+Kb+':';var Xf=sE[Yf];var Cg='';var U=Xf.indexOf(Bg);var Dg=new Date();var Eg,Fg,Gg,Hg,Fd;var Ig,Jg,Kg,Lg;if(Xf=='')
Xf='#';if(U>-1)
{Fg=Xf.substr(U+Bg.length,3+Yf);if(U>0)
Cg=Xf.substr(0,U);Eg=Xf.length-U-Bg.length-3-Yf;if(Eg>0)
Cg+=Xf.substr(U+Bg.length+3+Yf,Eg);Xf=Cg;Gg=new Date(Ag.indexOf(Fg.charAt(0))+2000,Ag.indexOf(Fg.charAt(1))-1,Ag.indexOf(Fg.charAt(2)));Dg.setHours(0);Dg.setMinutes(0);Dg.setSeconds(0);Hg=(Dg.getTime()-Gg.getTime())/1000/60/60/24;intAltWTag=(Gg.getDay()==0?7:Gg.getDay());intNeuWTag=(Dg.getDay()==0?7:Dg.getDay());intAltMTag=Gg.getDate();intNeuMTag=Dg.getDate();Zf=((Hg>0.1)?'1':'0')+(((Hg>6)||(intAltWTag>intNeuWTag))?'1':'0')+((((Hg>29)||(intAltMTag>intNeuMTag))&&(Yf!=1&&Yf!=14))?'1':'0');if(Yf==1||Yf==14)
k=Ag.indexOf(Fg.charAt(3));}Fg='#'+Kb+':';Fd=Dg.getYear();if(Fd<1900)
Fd+=1900;Fg+=Ag.charAt(Fd-2000);Fg+=Ag.charAt(Dg.getMonth()+1);Fg+=Ag.charAt(Dg.getDate());if(Yf==1||Yf==14)
{k++;if(k>21)
k=21;Fg+=Ag.charAt(k);Zf+=Ag.charAt(k);}Xf=Fg+Xf;wE(Xf,Yf);return Zf;}function yE(Bg,Yf,Mg)
{var Ma,Na,Eg,Ng,Og;var Xf=sE[Yf];var Cg='';var Pg='';var Qg=-1;if(Xf=='')
Xf='#';Bg='#'+Bg+'-';Ma=Xf.indexOf(Bg);if(Ma!=-1)
Na=Xf.indexOf('#',Ma+1);if((Ma!=-1)&&(Na!=1))
{Ng=Xf.substring(Ma+Bg.length,Na);if(Ma>0)
Cg=Xf.substr(0,Ma);Eg=Xf.length-Na;if(Eg>0)
Cg+=Xf.substr(Na,Eg);Xf=Cg;if(Yf==6)
{Og=Ng.split('-');Pg=Og[0];Ng=Og[1];}Qg=Mg-parseInt(Ng,10);if(Qg>1200)
Qg=-1;}sE[Yf]=Xf;return [Qg,Pg];}function zE(c)
{var Rg=new Date();var Qg=Rg.getHours()*60*60+Rg.getMinutes()*60+Rg.getSeconds();var Sg,Tg;Sg=yE(Ads_wid,6,Qg);Tg=yE(c,5,Qg);var Ug=(Sg[0]==-1);var Vg=(Tg[0]==-1);var Wg=(Ug?'1':'0')+(Vg?'1':'0');if(!Ug)
Wg+=jD(Sg[0],4)+Sg[1];wE('#'+Ads_wid+'-'+Ads_iid+'-'+Qg+sE[6],6);wE('#'+c+'-'+Qg+sE[5],5);return Wg;}function aF()
{xA=aD();var l,Xg,Pb,Yg,Zg,Ah,Bh,Ch,Yf;var Ja=document.cookie;var Sf=(Ja.toLowerCase().indexOf('sestest')>-1);document.cookie=xA+'SESTEST=1'+bD(-1);var Dh=Ja.split(';');var k=Dh.length;var Jb=new Date();tE=Math.round(Jb.getTime()/1000/60);sE=['','',[],'','','','',[],[],[],dB,'',[],'',''];for(l=0;l<k;l++)
{Yf=-1;Ah=Dh[l].split('=');Pb=Ah[0];Zg=Ah[1];if(Pb.charAt(0)==' ')
Pb=Pb.substr(1,Pb.length-1);if(Pb.substr(0,xA.length)==xA)
Yg=Pb.substring(xA.length,Pb.length);else
Yg='';if(Yg=='KIDYMD')
sE[1]=Zg;else if(Yg=='WIDYMD')
sE[0]=Zg;else if(Pb=='BSUID')
sE[3]=Zg;else if(Pb=='BNDLVL')
sE[10]=Zg;else if(Yg=='VISKAM')
sE[5]=Zg;else if(Yg=='VISWEB')
sE[6]=Zg;else if(Yg=='FRQSTR')
{Ah=Zg.split(',');sE[2]=uE(Ah[0],tE,Sf);sE[7]=uE(Ah[1],tE,Sf);sE[8]=uE(Ah[2],tE,Sf);sE[9]=uE(Ah[3],tE,Sf);sE[12]=uE(Ah[4],tE,Sf);}if(Yg=='KIDCYMD')
sE[14]=Zg;else if(Yg=='WIDCYMD')
sE[13]=Zg;}if(Ads_uid!='')
{Dh=Ads_userdata.split(';');k=Dh.length;sE[2]=[];for(l=1;l<(k-1);l++)
{Ah=Dh[l].split(',');sE[2][Ah[0]]=[Ah[1],1];}}if(sE[3]=='1')
zA=true;}function bF(c,Lc)
{var Eh,Fh,Ad,Gh;var Hh='';xA=aD();var Ih=KAS[Lc][4][5];if(KAS[Lc][4][4]>0)
Hh=bD(Ih);else if((KAS[Lc][5]&1)>0)
{Hh=bD(20);Ih=20;}if(Hh!='')
{Ad=parseInt(dF(c,2)+1,10);if(Ads_uid!='')
{Eh=Ads_userdata.split(';'+c+',');if(Eh.length==2)
{Fh=Ads_userdata.split(','+c+';');Ads_userdata=Eh[0]+';'+Fh[1];}Ads_userdata+=c+','+Ad+','+Ih+','+c+';';Gh=new Image();Gh.src='http://uboot.as-eu.falkag.net/usr?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random();}else
eF(c,2,Ad,Ih);}}function cF(c,Lc,d,p,Jh)
{xA=aD();var v,Ja;bF(c,Lc);if(d>0)
{if(BAS[p][2][4]>0)
eF(d,9,dF(d,9)+1,BAS[p][2][5]);}if(((KAS[Lc][4][22]&1)>0)&&(IAS[4]>0))
eF(Ads_wid,7,dF(Ads_wid,7)+1,IAS[5]);if(((KAS[Lc][4][22]&2)>0)&&(IAS[6]>0))
eF(Ads_nid,8,dF(Ads_nid,8)+1,IAS[7]);if ((typeof(IAS[17])!='undefined')&&(typeof(aC[Ads_wid])!='undefined')&&(typeof(KAS[Lc][13])!='undefined'))
{if(((KAS[Lc][4][22]&4)>0)&&(KAS[Lc][13]>0)&&(aC[Ads_wid].length>0)&&(typeof(aC[Ads_wid][KAS[Lc][13]])!='undefined'))
{arrFamily=aC[Ads_wid][KAS[Lc][13]];eF(arrFamily[0],12,dF(arrFamily[0],12)+1,arrFamily[2]);}}Ja=vE(sE[2],tE)+',' +vE(sE[7],tE)+',' +vE(sE[8],tE)+',' +vE(sE[9],tE)+',' +vE(sE[12],tE);document.cookie=xA+'FRQSTR='+Ja+bD(60*24*365);v=xE(1,c);v='&bls3='+v.substr(0,3)+xE(0,Ads_wid)+v.substr(3,1);document.cookie=xA+'WIDYMD='+sE[0]+bD(60*24*30);document.cookie=xA+'KIDYMD='+sE[1]+bD(60*24*30);v+='&bls4='+zE(c);document.cookie=xA+'VISKAM='+sE[5]+bD(20);document.cookie=xA+'VISWEB='+sE[6]+bD(20);strClickAuswertung=xE(14,c);v+='&ucl='+strClickAuswertung.substr(0,3)+xE(13,Ads_wid)+strClickAuswertung.substr(3,1);if(zA)
v+='&uid=1';return v;}function dF(Kb,Nd)
{if(typeof(sE[Nd][''+Kb+''])!='undefined')
return parseInt(sE[Nd][''+Kb+''],10);else
return 0;}function eF(Kb,Nd,Ad,Ih)
{if(typeof(sE[Nd][''+Kb+''])!='undefined')
sE[Nd][''+Kb+''][0]=Ad;else
sE[Nd][''+Kb+'']=[Ad,Ih];}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000024-2)
function tD(Wb,Xb)
{var l=0;var k=Wb.length;if(k==0)
return -1;while((l<k-1)&&(Xb>Wb[l][1]))
{Xb-=Wb[l][1];l++;}return Wb[l][0];}function uD(Yb,Zb,Ac)
{var l,Bc,Cc,Dc;if(Yb>Ac)
{Bc=Ac/Yb;for(l=Zb;l<lB.length;l++)
lB[l][1]*=Bc;Yb=Ac;}Ac-=Yb;return Ac;}function vD()
{var Ec,Fc,Gc,Hc,Ic;var Jc=-2;var Kc=KAS.length;var Ac=100;var Lc,c,Dc,Mc,Nc,Oc,Pc,Qc,Rc;var Yb=0;var Zb;lB=[];for (Lc=0;Lc<Kc;Lc++)
{Ic=((KAS[Lc][5]&2)>0);if(KAS[Lc][2]!=Jc)
{if(Jc!=-2)
Ac=uD(Yb,Zb,Ac);Jc=KAS[Lc][2];Yb=0;Zb=lB.length;}Mc=KAS[Lc][8];Nc=KAS[Lc][10];Oc=IAS[10];if((Oc-Nc)>0)
Mc=Mc*Oc/(Oc-Nc);Dc=KAS[Lc][1];if(Mc<=0)
Mc=Dc;Pc=(Dc/Mc-1)*2+1;var Sc=Pc;var Tc=false;if (Pc>10||Pc<0.1)
Tc=true;if(Pc>10)
Pc=10;else if (Pc<0.1)
Pc=0.1;if (Tc)
lD(1,'Factor (before:after)',Sc+':'+Pc);Qc=KAS[Lc][3];Dc=Dc*Pc*100/((Qc==0)?100:Qc);if(isNaN(Dc))
Dc=0;Hc=KAS[Lc][4];Ec=nE(Hc,0,KAS[Lc][0],((KAS[Lc][5]&4)>0),Lc);Gc=false;if(Hc.length>0)
{Gc=((Hc[0]==0)&&!((Hc[2]==0)&&(Hc[3]==1439)));Fc=(!Gc||lE(Hc[2],Hc[3]));if(Gc)
Dc=Dc*100/KAS[Lc][9];if(Ec&&!Fc&&!Ic)
{qA+='9'+KAS[Lc][0]+'-';}Ec=(Ec&&Fc);}if((KAS[Lc][5]&8)>0)
Dc=KAS[Lc][1];if(Ic&&Ec)
{c=KAS[Lc][0];rA+=c+'-';bF(c,Lc);}else if(Ec)
{lB[lB.length]=[Lc,Dc,Gc,Dc];Yb+=Dc;}else
{}}Ac=uD(Yb,Zb,Ac);}function wD()
{vD();var Uc,Lc,l,Dc;var Kc=lB.length;var Vc=0;for (Lc=0;Lc<Kc;Lc++)
{l=lB[Lc][0];Dc=lB[Lc][1];Uc=Math.round(Dc/lB[Lc][3]*10)-1;if(Uc>9)
Uc=9;if((Uc>=0)&&(KAS[l][0]>0))
qA+=Uc+''+KAS[l][0]+'-';Vc+=Dc;}return tD(lB,Vc*Math.random());}function xD(Lc,c)
{var Wc=[];var Xc=BAS.length;var Yc=((KAS[Lc][5]&1)>0);var Vc=0;var p,Dc,Zc,Ad,Bd,Cd;var Dd=true;for (p=0;p<Xc;p++)
{strInhalt=BAS[p][21];Cd=((strInhalt.length<3)||(strInhalt.indexOf('#'+Ads_iid+'#')>-1));if(((Ads_xl>1)||(Ads_yl>1))&&((BAS[p][13]>1)||(BAS[p][14]>1)))
{Dd=((Ads_xl==BAS[p][13])&&(Ads_yl==BAS[p][14]));}if(Dd&&Cd&&nE(BAS[p][2],1,BAS[p][0],true,p))
{Dc=BAS[p][1];Wc[Wc.length]=[p,Dc];Vc+=Dc;}else
{}}Xc=Wc.length;if(Yc)
{Ad=dF(c,2);if(Xc>0)
p=Wc[Ad%Xc][0];else
p=-1;}else
p=tD(Wc,Vc*Math.random());return p;}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000024-2)
var yD=false;var zD;var aE;var bE =(typeof(bE)=='undefined')? 0:bE;function cE(Ed)
{return jD(Ed.getHours(),2)+':'+jD(Ed.getMinutes(),2)+':'+jD(Ed.getSeconds(),2);}function dE(Ed)
{var Fd=Ed.getYear();if(Fd<1900)
Fd+=1900;return jD(Fd,4)+'-'+jD(Ed.getMonth()+1,2)+'-'+jD(Ed.getDate(),2);}function eE()
{if(yD)
return;var Gd,Hd,Id,l,Jd;var Kd=new Date();var Ld=new Date();Ld.setTime(Kd-0+parseInt(Ads_T[9],10));Gd=sE[1].split('#');Hd=Gd.length-1;Id=',';for(l=1;l<Hd;l++)
{Jd=Gd[l].split(':');Id+=Jd[0]+',';}yD=true;zD=';keyword='+escape(Ads_wrd) +';user-domain='+Ads_T[5] +';user-ip='+Ads_T[6] +';url='+escape(window.location.href) +';referrer='+escape(document.referrer) +';accept-language='+escape(Ads_T[7]) +';accept-charset='+escape(Ads_T[8]) +';user-agent='+escape(navigator.userAgent) +';browser-name='+escape(navigator.appName) +';browser-version='+escape(navigator.appVersion) +';flash-version='+oD(0) +';user-day='+(Kd.getDay()==0?7:Kd.getDay()) +';user-time='+cE(Kd) +';user-date='+dE(Kd) +';server-day='+(Ld.getDay()==0?7:Ld.getDay()) +';server-time='+cE(Ld) +';server-date='+dE(Ld) +';campaigns='+Id +';';if(navigator.appVersion.substring(0,1)>'3')
zD+='java='+(navigator.javaEnabled()?'1':'0') +';screen-width='+screen.width +';screen-height='+screen.height +';window-width='+(window.innerWidth?window.innerWidth:document.body.clientWidth) +';window-height='+(window.innerWidth?window.innerHeight:document.body.clientHeight) +';color-depth='+screen.colorDepth +';';}function fE(Md,k,Kb,Nd,Od,Pd,Qd)
{var Rd;if((k>0)&&(Md>0))
{Rd=((dF(Kb,Nd)<k)&&(zA||Qd));if((Rd?1:0)==Od)
return Od;aE[Pd]=Rd;}return 2;}function gE(Sd,Td,Ud,Od,Pd)
{var Rd;if(Sd.length>1)
{Rd=(Sd.indexOf('#'+Td+'#')!=-1);Rd=Ud>0?!Rd:Rd;if((Rd?1:0)==Od)
return Od;aE[Pd]=Rd;}return 2;}function hE(Md,Vd,Kb,Nd,Od,Pd,Qd)
{var Rd=true;if (typeof(Vd)=='undefined')
Vd=[];if (typeof(aC[Ads_wid])=='undefined')
aC[Ads_wid]=[];if(Md>0&&Kb>0)
{if ((Vd.length>0)&&(aC[Ads_wid].length==0))
{for (intI=0 ;intI<Vd.length ;intI++)
{aC[Ads_wid][Vd[intI][0]]=[Vd[intI][1],Vd[intI][2],Vd[intI][3]];if (Vd[intI][0]==Kb)
{sIndex=intI;}}if (typeof(sIndex)=='undefined')
return 2;intReturn=fE(Md,Vd[sIndex][2],Vd[sIndex][1],Nd,Od,Pd,Qd);return intReturn;}else if (aC[Ads_wid].length>0)
{if (typeof(aC[Ads_wid][Kb])=='undefined')
return 2;intReturn=fE(Md,aC[Ads_wid][Kb][1],aC[Ads_wid][Kb][0],Nd,Od,Pd,Qd);return intReturn;}}return 2;}function iE(Sd,Ud,Od,Wd,Pd)
{if(Sd=='')
return 2;var l,Fb,Xd,Yd,Zd,Ae,Be,Ce,De;var Ee='!"%&\'()*+,-./:;<=>?@[\\]^{|}~§ ';var Rd=false;Sd=Sd.substr(1,Sd.length-2);var Hc=Sd.split('#');var k=Hc.length;if(k>0)
{if(Wd)
{Fb='';Ae=Ads_wrd.length;for(l=0;l<Ae;l++)
{Zd=Ads_wrd.charAt(l);if(Ee.indexOf(Zd)!=-1)
Zd='#';Fb+=Zd;}Fb='#'+Fb.toLowerCase()+'#';Xd=Fb;}else
{Fb='#'+Ads_T[5]+'#';Xd='#'+Ads_T[6]+'#';}for(l=0;(l<k)&&(Rd==false);l++)
{Ce=Hc[l].toLowerCase();Be=false;if(Ce.substring(0,1)=='$')
{Ce=Ce.substring(1,Ce.length);Be=true;}Yd=false;De=Fb;if(Ce.substring(0,1)=='!')
{Ce=Ce.substring(1,Ce.length);De=Xd;Yd=true;}if(Wd)
Ce='#'+Ce;if(!Yd)
Ce+='#';Rd=(De.indexOf(Ce)!=-1);if(Be)
{Rd=!Rd;l=k;}}Rd=Ud>0?!Rd:Rd;if((Rd?1:0)==Od)
return Od;aE[Pd]=Rd;}return 2;}function jE(Fe,Ge)
{var He=[];var Ie=0;var l,Je;var k=Fe.length;for(l=0;l<k;l++)
{Je=Fe[l];if(Je>=0)
{He[Ie]=Ge[Je];Ie++;}else if(Je==-2)
{Ie--;He[Ie-1]=(He[Ie-1]&&He[Ie]);}else if(Je==-4)
{Ie--;He[Ie-1]=(He[Ie-1]||He[Ie]);}else if(Je==-3)
{He[Ie-1]=(!He[Ie-1]);}}return He[Ie-1];}function kE(Hc,Ke,Ud,Le,Me,Od,Pd)
{var Rd,Pb,Ne,Oe,Pe,Qe,z,Re;var Se,Te;var l=0;var k=Hc.length;var Ge=[];var Ue=Ke.toLowerCase();for(l=0;l<k;l++)
{Pb=Hc[l][0];Ne=Hc[l][1];z=Hc[l][2];Re=Hc[l][3];Se=Ue.indexOf(';'+Pb+'=');if(Se>-1)
{Te=Ke.indexOf(';',Se+1);if(Te>Se)
Qe=unescape(Ke.substring(Se+2+Pb.length,Te));else
Qe='';if(z==5)
z=1;if(z==1)
Oe=0;else
Oe='';if((Re==9)||(Re==10))
{Pe=Ne.split(';');if(Pe.length==2)
{Ne=Pe[0];Oe=Pe[1];}else
Re=0;}if(z==1)
{Qe=parseFloat(Qe);Ne=parseFloat(Ne);Oe=parseFloat(Oe);}if((Re>5)&&(Re<9))
{if (typeof(Qe)!='string')
Qe=Qe+'';if (typeof(Ne)!='string')
Ne=Ne+'';Qe=Qe.toLowerCase();Ne=Ne.toLowerCase();}if(Re==0)
Rd=(Qe==Ne);else if(Re==1)
Rd=(Qe!=Ne);else if(Re==2)
Rd=(Qe<Ne);else if(Re==3)
Rd=(Qe<=Ne);else if(Re==4)
Rd=(Qe>Ne);else if(Re==5)
Rd=(Qe>=Ne);else if(Re==6)
Rd=(Qe.indexOf(Ne)>-1);else if(Re==7)
Rd=(Qe.indexOf(Ne)<0);else if(Re==8)
{Rd=Qe.substr(0,Ne.length)==Ne;}else if(Re==9)
Rd=((Qe>=Ne)&&(Qe<=Oe));else if(Re==10)
Rd=((Qe<Ne)||(Qe>Oe));}else
{Rd=false;}if(Le==2)
Ge[l]=Rd;else
{if((Rd&&(Le==1))||(!Rd&&(Le==0)))
l=k;}}if(Le==2)
Rd=jE(Me,Ge);Rd=Ud>0?!Rd:Rd;if((Rd?1:0)==Od)
return Od;aE[Pd]=Rd;return 2;}function lE(Ve,We)
{var Kd=new Date();var Ld=new Date();Ld.setTime(Kd-0+parseInt(Ads_T[9],10));var Xe=Ld.getHours()*60+Ld.getMinutes();if(Ve<We)
Rd=((Xe>=Ve)&&(Xe<=We));else
Rd=((Xe>=Ve)||(Xe<=We));return Rd;}function mE(Ye,Ze)
{var k=Ye.length;var Af;try
{if(typeof(Ye.Ads_klist)=='string')
Ze+=Ye.Ads_klist+'#';}catch(objError) {}for(Af=0;Af<k;Af++)
{try
{Ze=mE(Ye.frames[Af],Ze);}catch(objError) {}}return Ze;}function nE(Hc,z,Kb,Qd,Bf)
{var Od=Hc[0];var Ud=Hc[1];var Rd,Cf,Df,Ef,Ff,Id,Gd,Hd,l,Gf,Hf,If,Jf;aE=[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true];if(Hc.length==0)
return true;if(((Od>0)||(z==1))&&!((Od==1)&&(Hc[2]==0)&&(Hc[3]==1439)))
{Rd=lE(Hc[2],Hc[3]);if((Rd?1:0)==Od)
return Rd;aE[0]=Rd;}Cf=fE(1,Hc[4],Kb,(z==0)?2:9,Od,1,Qd);if(Cf<2)
return Cf==1;if(z==0)
{Cf=fE(Hc[22]&1,IAS[4],Ads_wid,7,Od,12,Qd);if(Cf<2)
return Cf==1;Cf=fE(Hc[22]&2,IAS[6],Ads_nid,8,Od,13,Qd);if(Cf<2)
return Cf==1;Cf=hE(Hc[22]&4,IAS[17],KAS[Bf][13],12,Od,17,Qd);if(Cf<2)
return Cf==1;}Cf=gE(Hc[6],Ads_T[0],Ud&1,Od,2);if(Cf<2)
return Cf==1;Cf=gE(Hc[7],Ads_T[1],Ud&2,Od,3);if(Cf<2)
return Cf==1;Cf=gE(Hc[8],Ads_T[2],Ud&4,Od,4);if(Cf<2)
return Cf==1;Cf=gE(Hc[9],Ads_T[3],Ud&8,Od,5);if(Cf<2)
return Cf==1;Cf=gE(Hc[26],Ads_T[12],Ud&1024,Od,16);if(Cf<2)
return Cf==1;if(Hc[10].length>1)
{Rd=((Hc[10].indexOf('#'+Ads_T[4]+'#')!=-1)||(Hc[10].indexOf('#%'+Ads_T[10]+'#')!=-1)||(Hc[10].indexOf('#$'+Ads_T[11]+'#')!=-1));if((Ads_nid==7)&&(Ads_T[4]<1)&&(Hc[10].indexOf('#$14658#')!=-1)) Rd=true;Rd=(Ud&16)>0?!Rd:Rd;if((Rd?1:0)==Od)
return Od;aE[6]=Rd;}Cf=iE(Hc[11],Ud&32,Od,false,7);if(Cf<2)
return Cf==1;Cf=iE(Hc[12],Ud&64,Od,true,8);if(Cf<2)
return Cf==1;if(Hc[13].length>0)
{Cf=kE(Hc[13],';'+Ads_prf+';',Ud&128,Hc[15],Hc[17],Od,9);if(Cf<2)
return Cf==1;}if(Hc[14].length>0)
{eE();Cf=kE(Hc[14],zD,Ud&256,Hc[16],Hc[18],Od,10);if(Cf<2)
return Cf==1;}intBwdLevel=0;intBwdTyp=Hc[27];intBwdUser=sE[10];intBwdIP=Ads_T[13];if (intBwdTyp==1){oE();intBwdLevel=intBwdUser;}if (intBwdTyp==2){intBwdLevel=intBwdIP;}if (intBwdTyp==3){oE();intBwdLevel=((intBwdIP>intBwdUser)&&(intBwdUser!=0))?intBwdUser:(intBwdIP!=0)?intBwdIP:intBwdUser;}if (intBwdTyp==4){oE();intBwdLevel=(intBwdIP>intBwdUser)?intBwdIP:intBwdUser;}if((intBwdTyp==5)&&(intBwdUser==intBwdIP))
{ oE();intBwdLevel=intBwdIP;}Cf=gE(Hc[28],intBwdLevel,Ud&512,Od,11);if(Cf<2)
return Cf==1;Jf=Hc[23];if((z==0)&&(Jf>0))
{Id=Hc[24];if(Id.length>2)
Id=Id.substring(1,Id.length-1);Gd=Id.split('#');Hd=Gd.length;Gf=-1;strKList='#'+mE(top,'');for(l=0;(l<Hd)&&(Gf<0);l++)
{Hf=(strKList.indexOf('#'+Gd[l]+'#')>-1);if((Hf?1:4)==Jf)
Gf=0;if((Hf?3:2)==Jf)
Gf=1;}if(Gf<0)
Gf=((Jf==1)||(Jf==4))?1:0;if(Gf==Od)
return (Gf==1);aE[14]=(Gf==1);}l=Hc[25];if(l>0)
{Hf=IAS[8].indexOf('#'+l+':');if(Hf!=-1)
{Hf=IAS[8].indexOf(':',Hf);If=IAS[8].indexOf('#',Hf);Hf=IAS[8].substring(Hf+1,If);If=Ads_fcount[l];if(typeOf(If)=='undefined')
If=0;Rd=Hf>If;if((Rd?1:0)==Od)
return Rd;aE[15]=Rd;}}if(Od!=2)
return (Od==0);else
{return jE(Hc[19],aE);}}function oE()
{if((bE==0)&&zA&&(document.cookie.toLowerCase().indexOf('bndlvl')==-1))
bE=1;}function pE()
{if(bE!=1)
return;if((oD(1)<6)||pB)
{document.write('<applet codebase="'+jB[Ads_sec]+'/" code="bandwidth.class" id="bandwidth" name="bandwidth" width="0" height="0" mayscript="MAYSCRIPT"><param name="cbfunc" value="qE"></applet>');}else
{var Wa=window.location.hostname;document.write('<scr'+'ipt for="Ads_BWD" event="FSCommand(Lf,Mf)" language="VBScript"> \n on error resume next \n call Ads_BWD_DoFSCommand(Lf,Mf) \n </scr'+'ipt\>');document.write('<object id="Ads_BWD" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab" width="1" height="1">');document.write('<param name=movie value="'+jB[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+Wa+'&path='+jB[Ads_sec]+'"><param name=play value=true><param name=autoplay value=true>');document.write('<embed name="Ads_BWD" id="Ads_BWD" src="'+jB[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+Wa+'&path='+jB[Ads_sec]+'" play=true autoplay=true swLiveConnect=true width="1" height="1" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">');document.write('</embed></object>');}bE=2;}function qE(Kf)
{dB=0;Kf*=8;if(Kf==0)
dB=0;else if(Kf<9)
dB=1;else if(Kf<33)
dB=2;else if(Kf<65)
dB=3;else if(Kf<129)
dB=4;else if(Kf<385)
dB=5;else if(Kf<769)
dB=6;else if(Kf<1501)
dB=7;else if(Kf<3001)
dB=8;else
dB=9;document.cookie='BNDLVL='+dB+bD(60*24*7);}function Ads_BWD_DoFSCommand(Lf,Mf)
{qE(Mf/8);}function rE()
{var Nf=new Date();document.writeln('<scr'+'ipt language="Javascript"><!--');document.writeln('cB=new Date();');document.writeln('/'+'/--></scr'+'ipt>');yC(jB[Ads_sec]+'/dat/dlv/aslprebwd.js?'+Nf.getTime()+'0');}function Ads_PreBandwidth()
{var Of=new Date();var Pf=Math.round((8026/((Of.getTime()-cB.getTime()+1)/1000))/1024);qE(Pf);qC();}